### ISSUE TITLE
bug: resources (limits/requests) are not converted

### ISSUE THREAD

**Issue by norbjd** [norbjd/kueueleuleu#8]
Resources (limits/requests) are not copied to the initial pod containers to the kueueleuleu pod containers.

To reproduce:

```shell
VERSION=v0.1.1-0.20240531181637-df828fac90b6 # latest version as of now
go install github.com/norbjd/kueueleuleu/cmd/kueueleuleu@$VERSION

# create a pod manifest with resources
cat > pod.yaml <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
    - name: sleep
      image: alpine
      command:
        - sleep
      args:
        - 10
      resources:
        requests:
          cpu: 50m
          memory: 50M
        limits:
          cpu: 100m
          memory: 100M
EOF

# convert
kueueleuleu -f pod.yaml
```

Got:

```yaml
spec:
  containers:
  - name: sleep
    resources:
      limits:
        cpu: "0"
        memory: "0"
      requests:
        cpu: "0"
        memory: "0"
```

Expected:

```yaml
spec:
  containers:
  - name: sleep
    resources:
      limits:
        cpu: "100m"
        memory: "100M"
      requests:
        cpu: "50m"
        memory: "50M"
```

At first glance, this is because of the `gob` encoder used to deep copy the initial pod:

https://github.com/norbjd/kueueleuleu/blob/df828fac90b6b76c54318f9704c00aadcfac7f00/convert.go#L89

Indeed, this does not encode `resource.Quantity` structs properly, because it contains unexported fields, and from the [docs](https://pkg.go.dev/encoding/gob#hdr-Types_and_Values), with `gob`:

> Structs encode and decode only exported fields.

It works if we replace `gob` with `json` marshaler because `resource.Quantity` provides a `String()` method, but anyway I'm not sure encoding/decoding it's the right solution to deep copy. So maybe it's worth rewriting completely the `deepCopy` implementation.
